### ISSUE TITLE
Icon label flickering upon mouse hover.

### ISSUE THREAD

**Issue by Masilamani123** [nwg-piotr/nwg-dock-hyprland#68]
Description:
Whenever the mouse pointer is hovered over the icons displayed in the dock, at certain positions of the pointer, the label displaying the name of the app flickers.

Possible Diagnosis:
This happens in combination with the opacity of the app icon flickering. This is consistent with the diagnosis that there is some issue with the way the mouse 'hover' state has been defined for the app buttons in the source code.

**Comment by nwg-piotr** [comment]
Glitches like this sometimes appear on my machine at the office, that runs NVidia. There's nothing I could do in the dock code to avoid them.

**Comment by Masilamani123** [comment]
The flickering doesn't happen occasionally. It isn't a glitch. It happens
consistently whenever my mouse pointer is on specific locations on the app
icons in the dock, it is also not icon specific and happens to all of them
consistently. I put my mouse on an icon, the label keeps appearing and
disappearing, and the icon keeps switching from mouse hover state to
uncover state as indicated by varying opacity of the button. I am running
hyprland on my Intel integrated graphics card.

**Comment by hotsno** [comment]
I have the same issue

**Comment by arminius-smh** [comment]
The icon label starts flickering for me with an icon size > 38, see here:

https://github.com/user-attachments/assets/bc24b024-e2f6-4f7d-84b3-853f73bd612e

It seems like GTK decides that the tooltip can't render above the button after a certain size and decides to show the tooltip on the button, which then probably leads to focus issues and this flickering.

Is it maybe possible to create a custom tooltip window that's always above the button? This would probably fix this.

Otherwise, at least my workaround is to use icon size 38 for now
